import React from 'react'
import AboutCarousel from '@/components/About/AboutCarousel';
import AboutMeghdoot from '@/components/About/AboutMeghdoot';
import { Metadata } from 'next';
import TeamMeghdoot from '@/components/About/TeamMeghdoot';

export const metadata: Metadata = {
    title: 'About',
    description: 'Generated by create next app',
}

const About = () => {
    return (
        <div>
            <main>
                <AboutCarousel />
                <AboutMeghdoot />
                <TeamMeghdoot />
            </main>
        </div>
    )
}

export default About;