import React from 'react'
import { Metadata } from 'next';
import Information from '@/components/Contact/Information';

export const metadata: Metadata = {
  title: 'Contact',
  description: 'Generated by create next app',
}

const ContactUs = () => {
    return (
        <div>
            <main>
                <Information />
            </main>
        </div>
    )
}

export default ContactUs;
